name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

- name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: kayanjesus
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=#f0ad4e&dots=#161b22,#40c463,#30a14e,#216e39,#0e4429
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&color_snake=#f0ad4e&color_dots=#161b22,#9be9a8,#40c463,#30a14e,#216e39
        # O parâmetro color_snake=#f0ad4e deixa a "cabeça" amarela como o Pacman

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
